version: 2
sphinx:
  builder: html
  fail_on_warning: true
  configuration: docs/source/conf.py
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .