"""
Django settings for blueweather project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import logging.config
import os

from .config import Config
from .plugins import ExtensionsSingleton
from .plugins import map as plugin_map

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGGING_CONFIG = None
logging.config.dictConfig({
    'version': 1,
    'formatters': {
        'brief': {
            'format': '%(levelname)-5.5s [%(asctime)s - %(name)s] %(message)s',
            'datefmt': '%I:%M:%S %p'
        },
        'default': {
            'format': '%(levelname)-5.5s [%(asctime)s - %(name)s] %(message)s',
            'datefmt': '%m/%d/%Y %I:%M:%S %p'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'brief',
            'level': 'INFO',
            'stream': 'ext://sys.stdout'
        }
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console']
    },
    #  'incremental': True
})

# Configuration are user-defined settings. They are all stored in the CONFIG
# object, and follow a different convention from Settings to differentiate them
CONFIG = Config(os.path.join(BASE_DIR, "config.yml"))
CONFIG.load()
if CONFIG.modified:
    CONFIG.save()

# because django is set to reload, two instances of extensions will always be
# loaded. to stop this, use 'manage.py runserver --noreload'
EXTENSIONS = ExtensionsSingleton(CONFIG, True)


# Unit Conversions
UNITS = plugin_map.UnitConversion.all_conversions(EXTENSIONS.unitConversion)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

SECRET_KEY = CONFIG.secret_key
DEBUG = CONFIG.debug
ALLOWED_HOSTS = CONFIG.web.allowed_hosts

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blueweather.weather',
    'blueweather.accounts',
    'blueweather.plugins',
    'blueweather.api'
]

INSTALLED_APPS.extend(plugin_map.DjangoApp.getApps(EXTENSIONS.djangoApp))


# A list of apps that should be linked in the sidebar
# TODO automatically build SIDEBAR
SIDEBAR = CONFIG.web.sidebar or [
    {
        "category": "divider"
    },
    {
        "category": "item",
        "value": "blueweather.weather"
    },
    {
        "category": "item",
        "value": "blueweather.plugins"
    },
    {
        "category": "divider"
    },
    {
        "category": "item",
        "value": "blueweather.accounts"
    }
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware'
]

ROOT_URLCONF = 'blueweather.urls'

NPM_FILE_PATERNS = {
    'startbootstrap-sb-admin-2': [
        'css/*.min.css',
        'js/*.min.js',
        'scss/*'
    ]
}

STATIC_ROOT = "dist"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'npm.finders.NpmFinder'
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [
            os.path.join(BASE_DIR, "templates")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            "environment": "blueweather.jinja2.environment",
            "context_processors": [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ]
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blueweather.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = dict(
    [(k, v.get_data(BASE_DIR)) for k, v in CONFIG.web.databases.items()]
)


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = CONFIG.web.password_validation


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = CONFIG.time_zone

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = CONFIG.web.static_url
